version: '3'
services:

  ####Drupal7####################################################
  # d7:
  #   image: lawxen/drupal:7-nginx-php72
  #   # volumes:
  #   #   - ./d8/www/:/var/www/html
  #   container_name: d7
  #   ports:
  #     - 8081:80
  #   networks:
  #     - backend

  ####Drupal7 dev####################################################
  # d7dev:
  #   image: lawxen/drupal:7-nginx-php72-dev
  #   # volumes:
  #   #   - ./d8/www/:/var/www/html
  #   container_name: d7dev
  #   ports:
  #     - 8082:80
  #   networks:
  #     - backend

  ####Drupal9 dev####################################################
  d9:
    image: lawxen/drupal:9
    volumes:
      - ./www/:/var/www/
    container_name: d9
    ports:
      - 80:80
    networks:
      - backend

  ####Drupal9 dev contain xdebug #############################
  # d9dev:
  #   image: lawxen/drupal:9-dev
  #   # volumes:
  #   #   - ./d8/www/:/var/www/html
  #   container_name: d9dev
  #   ports:
  #     - 80:80
  #   networks:
  #     - backend

  ### Mariadb Container #######################################
  mariadb:
    image: mariadb:latest
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306"
    container_name: mariadb
    restart: always
    networks:
      - backend

### Redis Container #########################################
  # redis:
  #   image: latest
  #   container_name: redis
  #   environment:
  #     - REDIS_PASSWORD=c4200bc580
  #     - ALLOW_EMPTY_PASSWORD=no
  #   ports:
  #     - "6379"
  #   networks:
  #     - backend

### Network ###############################################
networks:
  backend:
    driver: "bridge"
