version: '3'
services:

  ####Drupal7####################################################
  # d7:
  #   image: lawxen/drupal:d7-php74
  #   # volumes:
  #   #   - ./html:/var/www/html
  #   container_name: d7
  #   ports:
  #     - 8081:80
  #   networks:
  #     - backend

  ####Drupal7 dev####################################################
  # d7dev:
  #   image: lawxen/drupal:d9-php74-dev
  #   # volumes:
  #   #   - ./html:/var/www/html
  #   container_name: d7dev
  #   ports:
  #     - 8082:80
  #   networks:
  #     - backend

  ####Drupal9 ####################################################
  d9:
    # image: lawxen/drupal:d9-php80-dev
    # image: lawxen/drupal:d9-php74
    image: lawxen/drupal:d9-php80
    volumes:
      - ./html:/var/www/html
    container_name: d9
    ports:
      - 80:80
    networks:
      - backend

  ### Mariadb Container #######################################
  mariadb:
    image: mariadb:latest
    volumes:
      - ./mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306"
    container_name: mariadb
    restart: always
    networks:
      - backend

### Redis Container #########################################
  # redis:
  #   image: latest
  #   container_name: redis
  #   environment:
  #     - REDIS_PASSWORD=c4200bc580
  #     - ALLOW_EMPTY_PASSWORD=no
  #   ports:
  #     - "6379"
  #   networks:
  #     - backend

### Network ###############################################
networks:
  backend:
    driver: "bridge"
